# SPDX-FileCopyrightText: 2023 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: <Author last name> <Author first name> firstname.lastname@idiap.ch
#
# SPDX-License-Identifier: LicenseRef-ProjectNameID

default:
  image: python:3.11  # specifies Docker image with correct python3 version
  tags: # specifies requirements for the gitlab runner
    - docker
    - linux


stages: # List of stages for jobs, and their order of execution
  - build
  - test

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - pip install .



unit-test-job:
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - pip install poetry
    - poetry lock && poetry install --no-interaction
    - poetry run coverage run -m pytest tests/*.py
    - poetry run coverage report -m
